### ISSUE TITLE
ENH: Plot ratio vs memory for pareto frontier

### ISSUE THREAD

**Issue by corneliusroemer** [mbhall88/compression_benchmark#3]
Great work! One idea for improvement:

A really useful way to visualize compression benchmarks is to plot ratio vs time/memory so one can get a pareto frontier (for each ratio, what's the fastest). Like this:
![image](https://github.com/mbhall88/compression_benchmark/assets/25161793/c085234a-ffaf-4034-b241-fa86ef23df67)

https://richg42.blogspot.com/2015/11/the-lossless-decompression-pareto.html

This is a good way to abstract away the arbitrary scale of compression levels - level 2 for gzip isn't the same as 2 for xz etc, all we care about is the line in the memory/ratio (or time/ratio) space, then look up what the level is that gets it for the tool that's best.

**Comment by mbhall88** [comment]
Good suggestions. I'll do this in the next update

**Comment by mbhall88** [comment]
https://github.com/mbhall88/compression_benchmark#rate-vs-ratio
